index.html
=> Add initial html

big-picture.js, index.html, style.css
I've added the initial CSS, so that we can see the cards on the DOM.
=> Add initial CSS

data/sample-users.js, src/UserRepository.js, test/UserRepository-test.js
=> Add userRepository file and test

index.html, style.css
=> Add classes to HTML

style.css
=> Change-card-heights

data/activity.js, data/hydration.js, data/sleep.js, data/users.js, index.html, normalize.css, src/User.js, src/UserRepository.js, src/scripts.js
=> Link files together

data/activity.js, data/hydration.js, data/sleep.js, data/users.js, index.html, src/User.js, src/UserRepository.js, src/scripts.js
=> DOM updates for user and userRepository

data/users.js, index.html, src/User.js, src/UserRepository.js, src/scripts.js, test/UserRepository-test.js
=> Add step goal comparison

data/users.js, src/User.js, src/UserRepository.js, src/scripts.js, test/UserRepository-test.js
=> Attempt to fix testing issue

src/SleepRepository.js, src/scripts.js
Co-Authored-by: Andreea Hanson <andreea.hanson7@gmail.com
=> Randomize a new user onload

data/hydration-sample.js, src/Hydration.js, test/Hydration-test.js
=> Return daily water intake

data/hydration-sample.js, src/Hydration.js, test/Hydration-test.js
=> Add returnAWeekWaterIntake function to Hydration

src/HydrationRepository.js, src/scripts.js, test/Hydration-test.js, test/HydrationRepository-test.js
=> Add hydration-repo tests

data/hydration.js, index.html, src/Hydration.js, src/scripts.js
=> Add script files for hydration to HTML

src/SleepRepository.js, test/SleepRepository-test.js
=> Add function for weeklySleepQualityAverageAllUsers

src/SleepRepository.js, test/SleepRepository-test.js
=> Function for SleepRepo longestDailySleeper

src/SleepRepository.js, test/SleepRepository-test.js
=> Add function to sleep-repo for worstDailySleeper

src/Sleep.js, test/Sleep-test.js
=> Add sleep functions and tests

src/Sleep.js, src/scripts.js
=> Add DOM updates for Hydration

index.html, src/scripts.js, style.css
=> Add functions for sleep dom updates

src/Activity.js, src/ActivityRepository.js, src/HydrationRepository.js, test/Activity-test.js, test/ActivityRepository-test.js
=> Add activity class methods and tests

src/ActivityRepository.js, test/ActivityRepository-test.js
=> Add activityRepository methods and tests

index.html, src/scripts.js, style.css
=> Add table for activity values in scripts.js

index.html, src/Activity.js, src/scripts.js, style.css, test/Activity-test.js
=> Add methods and tests for activity comparison

data/activity-sample.js, data/activity.js, data/sleep.js, index.html, src/Activity.js, src/scripts.js, test/Activity-test.js
=> Update dom with activity card

src/Sleep.js, test/Sleep-test.js
=> Eliminate decimals on sleep card averages

index.html, src/scripts.js, style.css
=> Add friends card in HTML in scripts.js

index.html, src/Activity.js, src/scripts.js, test/Activity-test.js
=> Complete friends card with function and DOM update

index.html, src/UserRepository.js, src/scripts.js, test/UserRepository-test.js
=> Add function to calculate average stride length and place on DOM

index.html, src/scripts.js, style.css
=> Re-format html and css with grid

index.html, src/scripts.js, style.css
=> Add user rankings
